ghena.nottes.net/routes/web.php
<?php

use App\Providers\LanguageServiceProvider;

include_once 'web_builder.php';
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('home');


Auth::routes();
#BackEnd

Route::group(['prefix' => 'admin', 'namespace'=>'Admin'], function () {

    # Error pages should be shown without requiring login
    Route::get('404', function () {
        return view('admin/404');
    });
    Route::get('500', function () {
        return view('admin/500');
    });
    # Lock screen
    Route::get('{id}/lockscreen', 'UsersController@lockscreen')->name('lockscreen');
    Route::post('{id}/lockscreen', 'UsersController@postLockscreen')->name('lockscreen');
    # All basic routes defined here
//    Route::get('login', 'AuthController@getSignin')->name('login');
    Route::get('login', 'AuthController@getSignin')->name('adminLogin');
    Route::get('signin', 'AuthController@getSignin')->name('signin');
    Route::post('signin', 'AuthController@postSignin')->name('postSignin');
    Route::post('signup', 'AuthController@postSignup')->name('signup');
    Route::post('forgot-password', 'AuthController@postForgotPassword')->name('forgot-password');
    Route::get('login2', function () {
        return view('admin/login2');
    });

    # Forgot Password Confirmation
    Route::get('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm')->name('forgot-password-confirm');
    Route::post('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm');

    # Logout
    Route::get('logout', 'AuthController@getLogout')->name('logout');

    # Account Activation
    Route::get('activate/{userId}/{activationCode}', 'AuthController@getActivate')->name('activate');
});

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {

    # Dashboard / Index
    Route::get('/', 'DashboardController@showHome')->name('dashboard');
    Route::get('/permission', 'DashboardController@showPersmissionDenied')->name('permission');

    # Vars
    Route::get('var', 'VarController@index')->name('index');
    Route::get('var/data', 'VarController@data')->name('var.data');
    Route::group(['prefix' => 'var'], function () {
        Route::get('{var}/delete', 'VarController@destroy')->name('var.delete');
        Route::get('{var}/confirm-delete', 'VarController@getModalDelete')->name('var.confirm-delete');
        Route::get('{var}/restore', 'VarController@getRestore')->name('var.restore');
    });
    Route::resource('var', 'VarController');

    # Roles
    Route::get('role', 'RoleController@index')->name('index');
    Route::get('role/data', 'RoleController@data')->name('role.data');
    Route::group(['prefix' => 'role'], function () {
        Route::get('{role}/delete', 'RoleController@destroy')->name('role.delete');
        Route::get('{role}/confirm-delete', 'RoleController@getModalDelete')->name('role.confirm-delete');
        Route::get('{role}/restore', 'RoleController@getRestore')->name('role.restore');
    });
    Route::resource('role', 'RoleController');

    # Collection
    Route::get('collection', 'CollectionController@index')->name('index');
    Route::get('collection/data', 'CollectionController@data')->name('collection.data');
    Route::group(['prefix' => 'collection'], function () {
        Route::get('{collection}/delete', 'CollectionController@destroy')->name('collection.delete');
        Route::get('{collection}/confirm-delete', 'CollectionController@getModalDelete')->name('collection.confirm-delete');
        Route::get('{collection}/restore', 'CollectionController@getRestore')->name('collection.restore');
    });
    Route::resource('collection', 'CollectionController');

    # Pages
    Route::get('page', 'PageController@index')->name('index');
    Route::get('page/data', 'PageController@data')->name('page.data');
    Route::group(['prefix' => 'page'], function () {
        Route::get('{page}/delete', 'PageController@destroy')->name('page.delete');
        Route::get('{page}/confirm-delete', 'PageController@getModalDelete')->name('page.confirm-delete');
        Route::get('{page}/restore', 'PageController@getRestore')->name('page.restore');
    });
    Route::resource('page', 'PageController');

    # Services
    Route::get('partner', 'PartnerController@index')->name('index');
    Route::get('partner/data', 'PartnerController@data')->name('partner.data');
    Route::group(['prefix' => 'partner'], function () {
        Route::get('{partner}/delete', 'PartnerController@destroy')->name('partner.delete');
        Route::get('{partner}/confirm-delete', 'PartnerController@getModalDelete')->name('partner.confirm-delete');
        Route::get('{partner}/restore', 'PartnerController@getRestore')->name('partner.restore');
    });
    Route::resource('partner', 'PartnerController');

    # Category
    Route::get('category', 'CategoryController@index')->name('index');
    Route::get('category/data', 'CategoryController@data')->name('category.data');
    Route::group(['prefix' => 'category'], function () {
        Route::get('{category}/delete', 'CategoryController@destroy')->name('category.delete');
        Route::get('{category}/confirm-delete', 'CategoryController@getModalDelete')->name('category.confirm-delete');
        Route::get('{category}/restore', 'CategoryController@getRestore')->name('category.restore');
    });
    Route::resource('category', 'CategoryController');

    # Cards
    Route::get('card', 'CardController@index')->name('index');
    Route::get('card/data', 'CardController@data')->name('card.data');
    Route::group(['prefix' => 'card'], function () {
        Route::get('{card}/delete', 'CardController@destroy')->name('card.delete');
        Route::get('{card}/confirm-delete', 'CardController@getModalDelete')->name('card.confirm-delete');
        Route::get('{card}/restore', 'CardController@getRestore')->name('card.restore');
    });

    Route::get('card/export', 'CardController@export')->name('card.export');
    Route::resource('card', 'CardController');
    Route::post('card/upload', 'CardController@upload')->name('card.upload');



    # News
    Route::get('news', 'NewsController@index')->name('index');
    Route::get('news/data', 'NewsController@data')->name('news.data');
    Route::group(['prefix' => 'news'], function () {
        Route::get('{news}/delete', 'NewsController@destroy')->name('news.delete');
        Route::get('{news}/confirm-delete', 'NewsController@getModalDelete')->name('news.confirm-delete');
        Route::get('{news}/restore', 'NewsController@getRestore')->name('news.restore');
    });
    Route::resource('news', 'NewsController');

    # Products
    Route::get('product', 'ProductController@index')->name('index');
    Route::get('product/data', 'ProductController@data')->name('product.data');
    Route::group(['prefix' => 'product'], function () {
        Route::get('{product}/delete', 'ProductController@destroy')->name('product.delete');
        Route::get('{product}/confirm-delete', 'ProductController@getModalDelete')->name('product.confirm-delete');
        Route::get('{product}/restore', 'ProductController@getRestore')->name('product.restore');
    });
    Route::resource('product', 'ProductController');
    Route::post('product/getSubCats', 'ProductController@getSubCats')->name('getSubCats');
    Route::post('product/getSubSubCats', 'ProductController@getSubSubCats')->name('getSubSubCats');

    Route::post('product/deleteProprietes', 'ProductController@deleteProprietes');
    Route::post('product/addProprietes', 'ProductController@addProprietes');

    # Emails
    Route::get('email', 'EmailController@index')->name('index');
    Route::get('email/data', 'EmailController@data')->name('email.data');
    Route::group(['prefix' => 'email'], function () {
        Route::get('{email}/delete', 'EmailController@destroy')->name('email.delete');
        Route::get('{email}/confirm-delete', 'EmailController@getModalDelete')->name('email.confirm-delete');
        Route::get('{email}/restore', 'EmailController@getRestore')->name('email.restore');
    });
    Route::resource('email', 'EmailController');

    # Locations/Localitatea
    Route::get('location', 'LocationController@index')->name('index');
    Route::get('location/data', 'LocationController@data')->name('location.data');
    Route::group(['prefix' => 'location'], function () {
        Route::get('{location}/delete', 'LocationController@destroy')->name('location.delete');
        Route::get('{location}/confirm-delete', 'LocationController@getModalDelete')->name('location.confirm-delete');
        Route::get('{location}/restore', 'LocationController@getRestore')->name('location.restore');
    });
    Route::resource('location', 'LocationController');

    # Sizes/Marimi
    Route::get('size', 'SizeController@index')->name('index');
    Route::get('size/data', 'SizeController@data')->name('size.data');
    Route::group(['prefix' => 'size'], function () {
        Route::get('{size}/delete', 'SizeController@destroy')->name('size.delete');
        Route::get('{size}/confirm-delete', 'SizeController@getModalDelete')->name('size.confirm-delete');
        Route::get('{size}/restore', 'SizeController@getRestore')->name('size.restore');
    });
    Route::resource('size', 'SizeController');

    # Color/Culoarea
    Route::get('color', 'ColorController@index')->name('index');
    Route::get('color/data', 'ColorController@data')->name('color.data');
    Route::group(['prefix' => 'color'], function () {

ghena.nottes.net/app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model {

    protected $table = 'roles';

    protected $fillable = [
        'name',
        'permissions',
        'slug',
    ];

    protected $guarded = ['id'];

}

ghena.nottes.net/app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;

use App\Http\Requests\RoleRequest;
use App\Models\Permission;
use App\Models\Role;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Support\Facades\URL;
use Yajra\DataTables\DataTables;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware(function ($request, $next){
            if(!Sentinel::getUser()->inRole('admin')) {
                Redirect::to(route('admin.permission'))->send();
            }
            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('admin.role.index');
    }

    public function data()
    {
        $tables = Role::select(['id', 'name'])->where('id','>',1);

        return DataTables::of($tables)
                ->addColumn('action', function (Role $tables) {
                    $html = '<a href="' . URL::to('admin/role/' . $tables->id . '/edit') . '" class="btn btn btn-primary btn-sm btn-sm-table"><i class="fa fa-edit"></i>'.trans('general.edit').'</a>&nbsp;&nbsp;&nbsp;';
                    $html.= '<a href="'.route('admin.role.confirm-delete', $tables->id).'" 
                                    class="btn btn btn-danger btn-sm delete-modal btn-sm-table"
                                    data-toggle="modal" data-target="#delete_confirm">
                                    <i class="fa fa-trash-o"></i>'.trans('general.delete').'
                              </a>';
                    return $html;
                })
                ->removeColumn('id')
                ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.role.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(RoleRequest $request)
    {
        $role = new Role($request->except('files','image'));
        $role->name = $request->input('name');
        $role->slug = str_slug($role->name);
        $role->save();

        if ($role->id) {
            if ($request->input('save_and_exit')) {
                return redirect('admin/role')->with('success', trans('role/message.success.create'));
            } else {
                return redirect('admin/role/'.$role->id.'/edit')->with('success', trans('role/message.success.create'));
            }
        } else {
            return Redirect::route('admin/role')->withInput()->with('error', trans('role/message.error.create'));
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Role $role
     * @return Response
     */
    public function edit(Role $role)
    {
        $rolesByID = Sentinel::findRoleById($role->id);
        $role_permissions = $rolesByID->permissions;
        $permissions = Permission::get();
        return view('admin.role.edit', compact('role','permissions','role_permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Role $role
     * @return Response
     */
    public function update(RoleRequest $request,Role $role)
    {
        $rolesByID = Sentinel::findRoleById($role->id);
        $role_permissions = $rolesByID->permissions;

        $role->name = $request->input('name');
        $role->save();

        $permissions = Permission::get();
        foreach ($permissions as $value) {
            // View
            $perm       = $value->slug.'.view';
            $perm_value = $request->get($value->slug.'_view') == 'on' ? true : false;
            if(isset($role_permissions[$perm])) {
                $rolesByID->updatePermission($perm,$perm_value);
            } else {
                $rolesByID->addPermission($perm,$perm_value);
            }
            // Edit
            $perm       = $value->slug.'.edit';
            $perm_value = $request->get($value->slug.'_edit') == 'on' ? true : false;
            if(isset($role_permissions[$perm])) {
                $rolesByID->updatePermission($perm,$perm_value);
            } else {
                $rolesByID->addPermission($perm,$perm_value);
            }
            // Delete
            $perm       = $value->slug.'.delete';
            $perm_value = $request->get($value->slug.'_delete') == 'on' ? true : false;
            if(isset($role_permissions[$perm])) {
                $rolesByID->updatePermission($perm,$perm_value);
            } else {
                $rolesByID->addPermission($perm,$perm_value);
            }
        }
        $rolesByID->save();

        if ($request->input('save_and_exit')) {
            return redirect('admin/role')->with('success', trans('role/message.success.update'));
        } else {
            return redirect('admin/role/'.$role->id.'/edit')->with('success', trans('role/message.success.update'));
        }

    }


    /**
     * Remove role.
     *
     * @param Role $role
     * @return Response
     */
    public function getModalDelete(Role $role)
    {
        $model = 'role';
        $item  = $role;
        $confirm_route = $error = null;
        try {
            $confirm_route = route('admin.role.delete', ['id' => $role->id]);
            return view('admin.layouts.modal_confirmation', compact('item','error', 'model', 'confirm_route'));
        } catch (GroupNotFoundException $e) {
            $error = trans('role/message.error.delete', compact('id'));
            return view('admin.layouts.modal_confirmation', compact('error','item_mame', 'model', 'confirm_route'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Role $role
     * @return Response
     */
    public function destroy(Role $role)
    {
        $img = public_path($role->image);
        if(file_exists($img)) {
            unlink($img);
        }
        if ($role->delete()) {
            return redirect('admin/role')->with('success', trans('role/message.success.destroy'));
        } else {
            return Redirect::route('admin/role')->withInput()->with('error', trans('role/message.error.delete'));
        }
    }

}

ghena.nottes.net/resources/views/admin/role/_footer.blade.php
{{-- page level scripts --}}
@section('footer_scripts')
    <script src="{{ asset('assets/vendors/moment/js/moment.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/daterangepicker/js/daterangepicker.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/materialdate/js/bootstrap-material-datetimepicker.js') }}" type="text/javascript"></script>

    <script type="text/javascript" src="{{ asset('assets/vendors/summernote/summernote.min.js') }}" ></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/jasny-bootstrap/js/jasny-bootstrap.js') }}" ></script>
    <script src="{{ asset('assets/vendors/select2/js/select2.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/bootstrap-tagsinput/js/bootstrap-tagsinput.js') }}" ></script>

    <script  src="{{ asset('assets/vendors/ckeditor/js/ckeditor.js') }}"  type="text/javascript"></script>
    <script  src="{{ asset('assets/vendors/ckeditor/js/jquery.js') }}"  type="text/javascript" ></script>
    <script  src="{{ asset('assets/vendors/ckeditor/js/config.js') }}"  type="text/javascript"></script>
    <script  src="{{ asset('assets/js/pages/editorPage.js') }}"  type="text/javascript"></script>

    <script>
        $(function() {
            $( ".image-select" ).click(function() {
                $('.fileupload-preview').remove();
            });
        });

    </script>
@stop

ghena.nottes.net/resources/views/admin/role/_form.blade.php
<input type="hidden" name="_token" value="{{ csrf_token() }}" />
<div class="row">
    <div class="col-sm-12">
        <div class="col-md-8">
            <div class="form-group{{ $errors->first('name', 'has-error') }}"  >
                <label for="page_name" class="">{{ trans('general.name') }}</label>
                {!! Form::text('name', null, array('class' => 'form-control', 'placeholder'=>trans('general.name'))) !!}
                <span class="help-block">{{ $errors->first('name', ':message') }}</span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group btn-area-form">
                <button type="submit" class="btn btn-primary">
                    <i class="glyphicon glyphicon-ok"></i>
                    @lang('general.save')
                </button>
                <button type="submit" class="btn btn-success" onclick="$('#save_and_exit').val(1);" >
                    <i class="glyphicon glyphicon-check"></i>
                    @lang('general.save_and_exit')
                </button>
                @if(Sentinel::getUser()->id == 1)
                    <a href="javascript:void(0)" class="btn btn-danger selectall">
                        Check All
                    </a>
                @endif
                <input type="hidden" value="0" name="save_and_exit" id="save_and_exit">
            </div>
        </div>
        @if(isset($permissions))
            <div class="col-md-12 row">
                @foreach($permissions as $value)
                    <div class="col-md-2">
                       <div class="permission-block">
                           <h4>{{ $value->name }}</h4>
                           <div class="from-group"  >
                               <input type="checkbox"
                                      name="{{ $value->slug }}.view"
                                      @if(isset($role_permissions[$value->slug.'.view']) && $role_permissions[$value->slug.'.view'] == true)
                                        checked="checked"
                                      @endif
                                      id="view-{{$value->id}}"
                                      class="checkbox_item"
                               >
                               <label for="view-{{$value->id}}" class="pointer">{{ trans('general.viewPermision') }}</label>
                           </div>
                           <div class="from-group"  >
                               <input type="checkbox"
                                      name="{{ $value->slug }}.edit"
                                      @if(isset($role_permissions[$value->slug.'.edit']) && $role_permissions[$value->slug.'.edit'] == true)
                                      checked="checked"
                                      @endif
                                      id="edit-{{$value->id}}"
                                      class="checkbox_item"
                               >
                               <label for="edit-{{$value->id}}" class="pointer">{{ trans('general.edit') }}</label>
                           </div>
                           <div class="from-group"  >
                               <input type="checkbox"
                                      name="{{ $value->slug }}.delete"
                                      @if(isset($role_permissions[$value->slug.'.delete']) && $role_permissions[$value->slug.'.delete'] == true)
                                      checked="checked"
                                      @endif
                                      id="delete-{{$value->id}}"
                                      class="checkbox_item"
                               >
                               <label for="delete-{{$value->id}}" class="pointer">{{ trans('general.delete') }}</label>
                           </div>
                           <div class="clear"></div>
                       </div>
                    </div>
                @endforeach
            </div>
        @endif
    </div>
</div>
@section('footer_scripts')
<script>
    $(function () {
        $('.selectall').click(function () {
            $('.permission-block').find(':checkbox').attr('checked','checked');
            $(".checkbox_item").prop('checked', 'checked');
            $(".checkbox_item").attr('checked', 'checked');
        });
    });
</script>
@stop

ghena.nottes.net/resources/views/admin/role/_head.blade.php
{{-- page level styles --}}
@section('header_styles')

    <link href="{{ asset('assets/vendors/summernote/summernote.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/jasny-bootstrap/css/jasny-bootstrap.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/select2/css/select2.min.css') }}" type="text/css" />
    <link href="{{ asset('assets/vendors/bootstrap-tagsinput/css/bootstrap-tagsinput.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/vendors/daterangepicker/css/daterangepicker.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/css/pages/page.css') }}" rel="stylesheet" type="text/css">

    <!--end of page level css-->
@stop

ghena.nottes.net/resources/views/admin/role/create.blade.php
@extends('admin/layouts/default')

{{-- Page title --}}
@section('title')
    @lang('role/title.create') @parent
@stop

@include('admin.role._head')

{{-- Page content --}}
@section('content')
<section class="content-header">
    <h1>
        @lang('role/form.add')
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}"> <i class="material-icons breadmaterial">home</i>
                @lang('general.dashboard')
            </a>
        </li>
        <li >
            <a href="{{ URL::to('admin/role') }}">
                @lang('role/form.list')
            </a>
        </li>
        <li class="active">
            @lang('role/form.add')
        </li>
    </ol>
</section>
<!--section ends-->
<section class="content paddingleft_right15">
    <!--main content-->
    <div class="row">
        <div class="the-box no-border">
            {!! Form::open(array('url' => URL::to('admin/role'), 'method' => 'post', 'class' => 'bf', 'files'=> true)) !!}
                @include('admin.role._form')
            {!! Form::close() !!}
        </div>
    </div>
    <!--main content ends-->
</section>
@stop

@include('admin.role._footer')

ghena.nottes.net/resources/views/admin/role/edit.blade.php
@extends('admin/layouts/default')

{{-- Web site Title --}}
@section('title')
    @lang('role/title.edit')
    @parent
@stop

@include('admin.role._head')

{{-- Page content --}}
@section('content')
    <section class="content-header">
        <h1>
            @lang('role/form.edit')
        </h1>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('admin.dashboard') }}"> <i class="material-icons breadmaterial">home</i> Dashboard
                </a>
            </li>
            <li >
                <a href="{{ URL::to('admin/role') }}">
                    @lang('role/form.list')
                </a>
            </li>
            <li class="active">
                @lang('role/form.edit')
            </li>
        </ol>
    </section>
    <!--section ends-->
    <section class="content paddingleft_right15">
        <!--main content-->
        <div class="row">
            <div class="the-box no-border">
                {!! Form::model($role, array('url' => URL::to('admin/role/' . $role->id), 'method' => 'put', 'class' => 'bf', 'files'=> true)) !!}
                    @include('admin.role._form')
                {!! Form::close() !!}
            </div>
        </div>

        <!--main content ends-->
    </section>
@stop

@include('admin.role._footer')

ghena.nottes.net/resources/views/admin/role/index.blade.php
@extends('admin.layouts.default')

{{-- Page title --}}
@section('title')
    @lang('role/form.name')
    @parent
@stop

{{-- page level styles --}}
@section('header_styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap.css') }}" />
    <link href="{{ asset('assets/css/pages/tables.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/css/pages/page.css') }}" rel="stylesheet" type="text/css">
@stop

{{-- Page content --}}
@section('content')

    <section class="content-header">
        <h1> @lang('role/form.name')</h1>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('admin.dashboard') }}">
                    <i class="material-icons breadmaterial">home</i>
                    @lang('general.dashboard')
                </a>
            </li>
            <li class="active">@lang('role/form.name')</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content paddingleft_right15">
        <div class="row">
            <div class="panel panel-primary blog_page">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left">
                        <i class="fa fa-bars"></i>
                        @lang('role/title.list')
                    </h4>
                    <div class="pull-right">
                        <a href="{{ URL::to('admin/role/create') }}" class="btn btn-sm btn-default">
                            <i class="material-icons add">add</i> @lang('general.add')
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="table1">
                            <thead>
                                <tr class="filters">
                                    <th>@lang('role/table.name')</th>
                                    <th>@lang('general.options')</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>    <!-- row-->
    </section>

@stop

@section('footer_scripts')
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap.js') }}"></script>
    <script>
        $(function() {
            var table = $('#table1').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{!! route('admin.role.data') !!}',
                order: [[ 1, "desc" ]],
                columns: [
                    { data: 'name', name: 'name' },
                    { data: 'action', name: 'action', width:'200px', orderable: false, searchable: false },

                ]
            });
        });
    </script>
    <div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="blogpage_delete_confirm_title" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
    <script>
        $(function () {$('body').on('hidden.bs.modal', '.modal', function () {$(this).removeData('bs.modal');});});
        $(document).on("click", ".blogpage_exists", function () {
            var group_name = $(this).data('name');
            $(".modal-header h4").text( group_name+" page" );
        });</script>
@stop